version: "3"

services:
  app:
    container_name: app
    build: ./docker/app
    env_file:
      - .env
    environment:
      - DB_CONNECTION=mysql
      - DB_DATABASE=main
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
  db:
    container_name: db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST="%"
      - TZ="Asia/Tokyo"
